spring:
  application:
    name: app
  cloud:
    config:
      uri: http://localhost:8888
      username: root
      password: Jmt123456
  profiles:
    active: dev
  config:
    import: "configserver:"

server:
  port: 8181

name: xyz
