server:
  port: ${PORT:8081} # 默认端口 8081，可以通过 PORT 环境变量或 server.port 系统属性覆盖

spring:
  application:
    name: provider-service # 服务名称，所有实例共享

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/ # Eureka 服务器地址
  instance:
    lease-renewal-interval-in-seconds: 5 # 心跳间隔
    lease-expiration-duration-in-seconds: 10 # 服务过期时间
    prefer-ip-address: true # 优先使用IP地址注册

# 日志级别，方便调试
logging:
  level:
    com.example.provider: DEBUG
    org.springframework.cloud.client.discovery: TRACE